name: Check devpod.yaml changes
on:
  pull_request:
    paths:
      - ".devpod.yml"
      - ".github/workflows/check-devpodyaml.yml"

jobs:
  notify:
    name: Build and upload model
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        uses: KeisukeYamashita/create-comment@v1
        with:
          number: ${{ github.event.pull_request.number }}
          comment: |
            :warning: Hey reviewer! BE CAREFUL :warning:
            Review the code before opening in your Gitpod. `.devpod.yml` was changed and it might be harmful.
